// Mock Countries Data
export const countries = [
  { id: 'c1', countryName: 'United Kingdom' },
  { id: 'c2', countryName: 'United States' },
  { id: 'c3', countryName: 'Canada' },
  { id: 'c4', countryName: 'Australia' },
  { id: 'c5', countryName: 'Germany' },
  { id: 'c6', countryName: 'New Zealand' },
];

// Mock States Data
export const states = [
  { id: 's1', sysCountryId: 'c1', stateName: 'England' },
  { id: 's2', sysCountryId: 'c1', stateName: 'Scotland' },
  { id: 's3', sysCountryId: 'c2', stateName: 'California' },
  { id: 's4', sysCountryId: 'c2', stateName: 'New York' },
  { id: 's5', sysCountryId: 'c3', stateName: 'Ontario' },
  { id: 's6', sysCountryId: 'c4', stateName: 'New South Wales' },
];

// Mock Cities Data
export const cities = [
  { id: 'ct1', sysStateId: 's1', cityName: 'London' },
  { id: 'ct2', sysStateId: 's1', cityName: 'Manchester' },
  { id: 'ct3', sysStateId: 's2', cityName: 'Edinburgh' },
  { id: 'ct4', sysStateId: 's3', cityName: 'Los Angeles' },
  { id: 'ct5', sysStateId: 's4', cityName: 'New York City' },
  { id: 'ct6', sysStateId: 's5', cityName: 'Toronto' },
  { id: 'ct7', sysStateId: 's6', cityName: 'Sydney' },
];

// Mock Academic Degrees
export const academicDegrees = [
  { id: 'd1', degreeName: 'High School', gpaScale: 100, levelOrder: 1 },
  { id: 'd2', degreeName: 'A-Levels', gpaScale: 100, levelOrder: 2 },
  { id: 'd3', degreeName: 'Bachelor\'s Degree', gpaScale: 4.0, levelOrder: 3 },
  { id: 'd4', degreeName: 'Master\'s Degree', gpaScale: 4.0, levelOrder: 4 },
  { id: 'd5', degreeName: 'PhD', gpaScale: 4.0, levelOrder: 5 },
];

// Mock Programmes
export const programmes = [
  { id: 'p1', name: 'Computer Science' },
  { id: 'p2', name: 'Business Administration' },
  { id: 'p3', name: 'Engineering' },
  { id: 'p4', name: 'Medicine' },
  { id: 'p5', name: 'Law' },
  { id: 'p6', name: 'Arts & Humanities' },
  { id: 'p7', name: 'Data Science' },
];

// Mock English Tests
export const englishTests = [
  { id: 'et1', testName: 'IELTS', maxScore: 9 },
  { id: 'et2', testName: 'TOEFL', maxScore: 120 },
  { id: 'et3', testName: 'PTE', maxScore: 90 },
  { id: 'et4', testName: 'Duolingo', maxScore: 160 },
];

// Mock Intakes
export const intakes = [
  { id: 'i1', name: 'Fall', intakeMonth: 9 },
  { id: 'i2', name: 'Spring', intakeMonth: 1 },
  { id: 'i3', name: 'Summer', intakeMonth: 5 },
];

// Mock Users
export const users = [
  {
    id: 'u1',
    email: 'john.doe@email.com',
    phone: '+1234567890',
    passwordHash: 'hashed',
    accountStatus: 'active',
    userType: 'lead',
    passResetTokenHash: null,
    passResetTokenExpiredAt: null,
    isPhoneVerified: true,
    failedLoginAttempts: 0,
    lockedUntil: null,
  },
  {
    id: 'u2',
    email: 'jane.smith@email.com',
    phone: '+1234567891',
    passwordHash: 'hashed',
    accountStatus: 'active',
    userType: 'lead',
    passResetTokenHash: null,
    passResetTokenExpiredAt: null,
    isPhoneVerified: true,
    failedLoginAttempts: 0,
    lockedUntil: null,
  },
  {
    id: 'u3',
    email: 'mike.johnson@email.com',
    phone: '+1234567892',
    passwordHash: 'hashed',
    accountStatus: 'active',
    userType: 'lead',
    passResetTokenHash: null,
    passResetTokenExpiredAt: null,
    isPhoneVerified: false,
    failedLoginAttempts: 0,
    lockedUntil: null,
  },
  {
    id: 'u4',
    email: 'sarah.wilson@email.com',
    phone: '+1234567893',
    passwordHash: 'hashed',
    accountStatus: 'active',
    userType: 'lead',
    passResetTokenHash: null,
    passResetTokenExpiredAt: null,
    isPhoneVerified: true,
    failedLoginAttempts: 0,
    lockedUntil: null,
  },
  {
    id: 'u5',
    email: 'admin@scolcrm.com',
    phone: '+1234567800',
    passwordHash: 'hashed',
    accountStatus: 'active',
    userType: 'admin',
    passResetTokenHash: null,
    passResetTokenExpiredAt: null,
    isPhoneVerified: true,
    failedLoginAttempts: 0,
    lockedUntil: null,
  },
];

// Mock Lead Profiles
export const leadProfiles = [
  {
    id: 'lp1',
    userId: 'u1',
    fullName: 'John Doe',
    dob: '1998-05-15',
    gender: 'male',
    address: '123 Main Street',
    city: 'New York',
    imgUrl: null,
    status: 'new',
    targetUniversity: 'University of Oxford',
  },
  {
    id: 'lp2',
    userId: 'u2',
    fullName: 'Jane Smith',
    dob: '1999-08-22',
    gender: 'female',
    address: '456 Oak Avenue',
    city: 'Los Angeles',
    imgUrl: null,
    status: 'contacted',
    targetUniversity: 'Harvard University',
  },
  {
    id: 'lp3',
    userId: 'u3',
    fullName: 'Mike Johnson',
    dob: '1997-12-10',
    gender: 'male',
    address: '789 Pine Road',
    city: 'Chicago',
    imgUrl: null,
    status: 'qualified',
    targetUniversity: 'University of Toronto',
  },
  {
    id: 'lp4',
    userId: 'u4',
    fullName: 'Sarah Wilson',
    dob: '2000-03-28',
    gender: 'female',
    address: '321 Elm Street',
    city: 'Houston',
    imgUrl: null,
    status: 'enrolled',
    targetUniversity: 'University of Melbourne',
  },
  {
    id: 'lp5',
    userId: 'u6',
    fullName: 'David Brown',
    dob: '1998-07-14',
    gender: 'male',
    address: '654 Cedar Lane',
    city: 'Phoenix',
    imgUrl: null,
    status: 'new',
    targetUniversity: 'Imperial College London',
  },
  {
    id: 'lp6',
    userId: 'u7',
    fullName: 'Emily Davis',
    dob: '1999-11-05',
    gender: 'female',
    address: '987 Birch Court',
    city: 'Philadelphia',
    imgUrl: null,
    status: 'contacted',
    targetUniversity: 'MIT',
  },
  {
    id: 'lp7',
    userId: 'u8',
    fullName: 'Chris Martinez',
    dob: '1997-02-20',
    gender: 'male',
    address: '147 Maple Drive',
    city: 'San Antonio',
    imgUrl: null,
    status: 'lost',
    targetUniversity: 'Stanford University',
  },
  {
    id: 'lp8',
    userId: 'u9',
    fullName: 'Amanda Taylor',
    dob: '2000-09-12',
    gender: 'female',
    address: '258 Walnut Street',
    city: 'San Diego',
    imgUrl: null,
    status: 'qualified',
    targetUniversity: 'University of Cambridge',
  },
];

// Mock Universities
export const universities = [
  {
    id: 'uni1',
    uniName: 'University of Oxford',
    sysCountryId: 'c1',
    sysStateId: 's1',
    sysCityId: 'ct1',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/200px-Oxford-University-Circlet.svg.png',
    website: 'https://www.ox.ac.uk',
    aboutUs: 'The University of Oxford is a collegiate research university in Oxford, England. There is evidence of teaching as early as 1096, making it the oldest university in the English-speaking world.',
    address: 'University Offices, Wellington Square, Oxford OX1 2JD',
    coverImageUrl: 'https://images.unsplash.com/photo-1580491934492-ea6df03f3b5b?w=1200',
    campusLifeLinks: ['https://youtube.com/oxford1', 'https://youtube.com/oxford2'],
    commission: 15,
  },
  {
    id: 'uni2',
    uniName: 'Harvard University',
    sysCountryId: 'c2',
    sysStateId: 's4',
    sysCityId: 'ct5',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/200px-Harvard_University_coat_of_arms.svg.png',
    website: 'https://www.harvard.edu',
    aboutUs: 'Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636, it is the oldest institution of higher learning in the United States.',
    address: 'Massachusetts Hall, Cambridge, MA 02138',
    coverImageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200',
    campusLifeLinks: ['https://youtube.com/harvard1'],
    commission: 12,
  },
  {
    id: 'uni3',
    uniName: 'University of Toronto',
    sysCountryId: 'c3',
    sysStateId: 's5',
    sysCityId: 'ct6',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Utoronto_coa.svg/200px-Utoronto_coa.svg.png',
    website: 'https://www.utoronto.ca',
    aboutUs: 'The University of Toronto is a public research university in Toronto, Ontario, Canada, on the grounds that surround Queen\'s Park.',
    address: '27 King\'s College Circle, Toronto, ON M5S 1A1',
    coverImageUrl: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59?w=1200',
    campusLifeLinks: [],
    commission: 10,
  },
  {
    id: 'uni4',
    uniName: 'University of Melbourne',
    sysCountryId: 'c4',
    sysStateId: 's6',
    sysCityId: 'ct7',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ec/University_of_Melbourne_logo.svg/200px-University_of_Melbourne_logo.svg.png',
    website: 'https://www.unimelb.edu.au',
    aboutUs: 'The University of Melbourne is a public research university located in Melbourne, Australia. Founded in 1853, it is Australia\'s second oldest university.',
    address: 'Parkville VIC 3010, Australia',
    coverImageUrl: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1200',
    campusLifeLinks: [],
    commission: 14,
  },
  {
    id: 'uni5',
    uniName: 'Imperial College London',
    sysCountryId: 'c1',
    sysStateId: 's1',
    sysCityId: 'ct1',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Imperial_College_London_crest.svg/200px-Imperial_College_London_crest.svg.png',
    website: 'https://www.imperial.ac.uk',
    aboutUs: 'Imperial College London is a public research university in London, United Kingdom. Imperial was established in 1907 by royal charter.',
    address: 'South Kensington Campus, London SW7 2AZ',
    coverImageUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200',
    campusLifeLinks: [],
    commission: 13,
  },
  {
    id: 'uni6',
    uniName: 'Technical University of Munich',
    sysCountryId: 'c5',
    sysStateId: null,
    sysCityId: null,
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Logo_of_the_Technical_University_of_Munich.svg/200px-Logo_of_the_Technical_University_of_Munich.svg.png',
    website: 'https://www.tum.de',
    aboutUs: 'The Technical University of Munich is a public research university in Munich, Germany. It is a member of TU9, an incorporated society of the largest and most notable German institutes of technology.',
    address: 'Arcisstraße 21, 80333 München, Germany',
    coverImageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200',
    campusLifeLinks: [],
    commission: 8,
  },
];

// Mock Courses
export const courses = [
  {
    id: 'course1',
    uniId: 'uni1',
    sysProgrammeId: 'p1',
    sysDegreeId: 'd3',
    courseName: 'BSc Computer Science',
    minSysDegreeId: 'd2',
    minGpa: 3.5,
  },
  {
    id: 'course2',
    uniId: 'uni1',
    sysProgrammeId: 'p2',
    sysDegreeId: 'd4',
    courseName: 'MBA Business Administration',
    minSysDegreeId: 'd3',
    minGpa: 3.0,
  },
  {
    id: 'course3',
    uniId: 'uni2',
    sysProgrammeId: 'p1',
    sysDegreeId: 'd3',
    courseName: 'BS Computer Science',
    minSysDegreeId: 'd2',
    minGpa: 3.7,
  },
  {
    id: 'course4',
    uniId: 'uni2',
    sysProgrammeId: 'p5',
    sysDegreeId: 'd3',
    courseName: 'Juris Doctor',
    minSysDegreeId: 'd3',
    minGpa: 3.5,
  },
  {
    id: 'course5',
    uniId: 'uni3',
    sysProgrammeId: 'p3',
    sysDegreeId: 'd3',
    courseName: 'BASc Engineering Science',
    minSysDegreeId: 'd2',
    minGpa: 3.3,
  },
  {
    id: 'course6',
    uniId: 'uni3',
    sysProgrammeId: 'p7',
    sysDegreeId: 'd4',
    courseName: 'MSc Data Science',
    minSysDegreeId: 'd3',
    minGpa: 3.2,
  },
  {
    id: 'course7',
    uniId: 'uni4',
    sysProgrammeId: 'p4',
    sysDegreeId: 'd3',
    courseName: 'Doctor of Medicine',
    minSysDegreeId: 'd2',
    minGpa: 3.8,
  },
  {
    id: 'course8',
    uniId: 'uni5',
    sysProgrammeId: 'p3',
    sysDegreeId: 'd4',
    courseName: 'MSc Mechanical Engineering',
    minSysDegreeId: 'd3',
    minGpa: 3.4,
  },
  {
    id: 'course9',
    uniId: 'uni6',
    sysProgrammeId: 'p1',
    sysDegreeId: 'd4',
    courseName: 'MSc Informatics',
    minSysDegreeId: 'd3',
    minGpa: 3.0,
  },
];

// Mock Course Intakes
export const courseIntakes = [
  {
    id: 'ci1',
    uniCourseId: 'course1',
    uniIntakeId: 'ui1',
    intakeYear: 2026,
    courseDuration: 36,
    applicationDeadline: '2026-01-15',
    tuitionFee: 38000,
    currency: 'GBP',
    initialDeposit: 5000,
    isActive: true,
  },
  {
    id: 'ci2',
    uniCourseId: 'course2',
    uniIntakeId: 'ui2',
    intakeYear: 2026,
    courseDuration: 24,
    applicationDeadline: '2026-03-01',
    tuitionFee: 45000,
    currency: 'GBP',
    initialDeposit: 8000,
    isActive: true,
  },
  {
    id: 'ci3',
    uniCourseId: 'course3',
    uniIntakeId: 'ui3',
    intakeYear: 2026,
    courseDuration: 48,
    applicationDeadline: '2026-01-01',
    tuitionFee: 55000,
    currency: 'USD',
    initialDeposit: 10000,
    isActive: true,
  },
  {
    id: 'ci4',
    uniCourseId: 'course5',
    uniIntakeId: 'ui4',
    intakeYear: 2026,
    courseDuration: 48,
    applicationDeadline: '2026-02-15',
    tuitionFee: 42000,
    currency: 'CAD',
    initialDeposit: 6000,
    isActive: true,
  },
];

// Mock University Intakes
export const universityIntakes = [
  { id: 'ui1', uniId: 'uni1', sysIntakeId: 'i1', intakeName: 'Fall 2026' },
  { id: 'ui2', uniId: 'uni1', sysIntakeId: 'i2', intakeName: 'Spring 2026' },
  { id: 'ui3', uniId: 'uni2', sysIntakeId: 'i1', intakeName: 'Fall 2026' },
  { id: 'ui4', uniId: 'uni3', sysIntakeId: 'i1', intakeName: 'Fall 2026' },
  { id: 'ui5', uniId: 'uni4', sysIntakeId: 'i2', intakeName: 'Spring 2026' },
];

// Mock Lead Academic Results
export const leadAcademicResults = [
  { id: 'lar1', leadId: 'lp1', sysDegreeId: 'd2', institute: 'City High School', gpa: 85, passingDate: '2016-06-15', isVerified: true },
  { id: 'lar2', leadId: 'lp1', sysDegreeId: 'd3', institute: 'State University', gpa: 3.6, passingDate: '2020-05-20', isVerified: true },
  { id: 'lar3', leadId: 'lp2', sysDegreeId: 'd2', institute: 'Lincoln High', gpa: 92, passingDate: '2017-06-10', isVerified: true },
  { id: 'lar4', leadId: 'lp3', sysDegreeId: 'd3', institute: 'Northwestern College', gpa: 3.4, passingDate: '2019-05-25', isVerified: false },
];

// Mock Lead English Test Results
export const leadEnglishTestResults = [
  { id: 'letr1', leadId: 'lp1', sysEngTestId: 'et1', testDate: '2025-01-15', overallScore: 7.5, isVerified: true },
  { id: 'letr2', leadId: 'lp2', sysEngTestId: 'et2', testDate: '2025-02-20', overallScore: 105, isVerified: true },
  { id: 'letr3', leadId: 'lp3', sysEngTestId: 'et1', testDate: '2025-03-10', overallScore: 6.5, isVerified: false },
  { id: 'letr4', leadId: 'lp4', sysEngTestId: 'et3', testDate: '2025-04-05', overallScore: 75, isVerified: true },
];

// Export all mock data
export default {
  countries,
  states,
  cities,
  academicDegrees,
  programmes,
  englishTests,
  intakes,
  users,
  leadProfiles,
  universities,
  courses,
  courseIntakes,
  universityIntakes,
  leadAcademicResults,
  leadEnglishTestResults,
};
